+ set echo on
+ RT=/users/PDS0325/sachitk26/packages/tart
+ DSET=e_coli
+ D_ROOT=/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli
+ PICKLE_ROOT=/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/picks
+ SAVE_ROOT=/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered
+ module load miniconda3
++ /apps/lmod/lmod/libexec/lmod bash load miniconda3
+ eval '__LMOD_REF_COUNT_LD_LIBRARY_PATH=/apps/miniconda3/4.10.3-py37/lib:1\;/opt/mvapich2/intel/19.0/2.3.3/lib:1\;/apps/gnu/8.4.0/lib64:1\;/apps/gnu/8.4.0/lib:1\;/opt/intel/19.0.5/debugger_2019/libipt/intel64/lib:1\;/opt/intel/19.0.5/compilers_and_libraries_2019/linux/lib/intel64_lin:1\;/opt/intel/19.0.5/compilers_and_libraries_2019/linux/daal/lib/intel64_lin:1\;/opt/intel/19.0.5/compilers_and_libraries_2019/linux/ipp/lib/intel64_lin:1\;/opt/intel/19.0.5/compilers_and_libraries_2019/linux/mkl/lib/intel64_lin:1\;/opt/intel/19.0.5/compilers_and_libraries_2019/linux/tbb/lib/intel64_lin/gcc4.4:1\;/opt/ddn/cci/lib:1\;/opt/ddn/ime/lib:1\;/opt/ddn/isa-l/lib:1;' export '__LMOD_REF_COUNT_LD_LIBRARY_PATH;' 'LD_LIBRARY_PATH=/apps/miniconda3/4.10.3-py37/lib:/opt/mvapich2/intel/19.0/2.3.3/lib:/apps/gnu/8.4.0/lib64:/apps/gnu/8.4.0/lib:/opt/intel/19.0.5/debugger_2019/libipt/intel64/lib:/opt/intel/19.0.5/compilers_and_libraries_2019/linux/lib/intel64_lin:/opt/intel/19.0.5/compilers_and_libraries_2019/linux/daal/lib/intel64_lin:/opt/intel/19.0.5/compilers_and_libraries_2019/linux/ipp/lib/intel64_lin:/opt/intel/19.0.5/compilers_and_libraries_2019/linux/mkl/lib/intel64_lin:/opt/intel/19.0.5/compilers_and_libraries_2019/linux/tbb/lib/intel64_lin/gcc4.4:/opt/ddn/cci/lib:/opt/ddn/ime/lib:/opt/ddn/isa-l/lib;' export 'LD_LIBRARY_PATH;' 'LMOD_FAMILY_PYTHON=miniconda3;' export 'LMOD_FAMILY_PYTHON;' 'LMOD_FAMILY_PYTHON_VERSION=4.10.3-py37;' export 'LMOD_FAMILY_PYTHON_VERSION;' '__LMOD_REF_COUNT_LOADEDMODULES=xalt/latest:1\;gcc-compatibility/8.4.0:1\;intel/19.0.5:1\;mvapich2/2.3.3:1\;modules/sp2020:1\;miniconda3/4.10.3-py37:1;' export '__LMOD_REF_COUNT_LOADEDMODULES;' 'LOADEDMODULES=xalt/latest:gcc-compatibility/8.4.0:intel/19.0.5:mvapich2/2.3.3:modules/sp2020:miniconda3/4.10.3-py37;' export 'LOADEDMODULES;' '__LMOD_REF_COUNT_MANPATH=/apps/miniconda3/4.10.3-py37/share/man:1\;/opt/mvapich2/intel/19.0/2.3.3/share/man:1\;/opt/intel/19.0.5/itac_latest/man:1\;/opt/intel/19.0.5/documentation_2019/en/debugger/gdb-igfx/man:1\;/opt/intel/19.0.5/inspector_2019/man:1\;/opt/intel/19.0.5/compilers_and_libraries_2019/linux/man/common:1\;/apps/lmod/lmod/share/man:1\;/opt/puppetlabs/puppet/share/man:1\;/opt/intel/19.0.5/vtune_amplifier/man:1\;/opt/intel/19.0.5/advisor/man:1;' export '__LMOD_REF_COUNT_MANPATH;' 'MANPATH=/apps/miniconda3/4.10.3-py37/share/man:/opt/mvapich2/intel/19.0/2.3.3/share/man:/opt/intel/19.0.5/itac_latest/man:/opt/intel/19.0.5/documentation_2019/en/debugger/gdb-igfx/man:/opt/intel/19.0.5/inspector_2019/man:/opt/intel/19.0.5/compilers_and_libraries_2019/linux/man/common:/apps/lmod/lmod/share/man::/opt/puppetlabs/puppet/share/man:/opt/intel/19.0.5/vtune_amplifier/man:/opt/intel/19.0.5/advisor/man;' export 'MANPATH;' 'MODULEPATH=/apps/lmodfiles/MPI/intel/19.0/mvapich2/2.3:/apps/lmodfiles/Compiler/intel/19.0:/apps/lmodfiles/Linux:/apps/lmodfiles/Core:/apps/lmod/lmod/modulefiles/Core;' export 'MODULEPATH;' 'OSC_FAMILY_PYTHON=miniconda3;' export 'OSC_FAMILY_PYTHON;' 'OSC_FAMILY_PYTHON_VERSION=4.10.3-py37;' export 'OSC_FAMILY_PYTHON_VERSION;' 'OSC_MINICONDA3_DIR=/apps/miniconda3/4.10.3-py37;' export 'OSC_MINICONDA3_DIR;' '__LMOD_REF_COUNT_PATH=/apps/xalt/xalt/bin:1\;/apps/miniconda3/4.10.3-py37/bin:1\;/usr/local/miniconda3/4.10.3-py37/bin:3\;/opt/osc/bin:3\;/users/PDS0325/sachitk26/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/bin/remote-cli:1\;/opt/mvapich2/intel/19.0/2.3.3/bin:1\;/apps/gnu/8.4.0/bin:1\;/opt/intel/19.0.5/itac_latest/bin:1\;/opt/intel/19.0.5/advisor/bin64:1\;/opt/intel/19.0.5/vtune_amplifier/bin64:1\;/opt/intel/19.0.5/inspector_2019/bin64:1\;/opt/intel/19.0.5/compilers_and_libraries_2019/linux/bin/intel64:1\;/usr/lib64/qt-3.3/bin:1\;/usr/local/bin:1\;/usr/bin:1\;/opt/puppetlabs/bin:1\;/users/PDS0325/sachitk26/local/ont-guppy/bin:3\;/usr/local/sbin:1\;/usr/sbin:1;' export '__LMOD_REF_COUNT_PATH;' 'PATH=/apps/xalt/xalt/bin:/apps/miniconda3/4.10.3-py37/bin:/usr/local/miniconda3/4.10.3-py37/bin:/opt/osc/bin:/users/PDS0325/sachitk26/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/bin/remote-cli:/opt/mvapich2/intel/19.0/2.3.3/bin:/apps/gnu/8.4.0/bin:/opt/intel/19.0.5/itac_latest/bin:/opt/intel/19.0.5/advisor/bin64:/opt/intel/19.0.5/vtune_amplifier/bin64:/opt/intel/19.0.5/inspector_2019/bin64:/opt/intel/19.0.5/compilers_and_libraries_2019/linux/bin/intel64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/opt/puppetlabs/bin:/users/PDS0325/sachitk26/local/ont-guppy/bin:/usr/local/sbin:/usr/sbin;' export 'PATH;' 'PYTHON_HOME=/apps/miniconda3/4.10.3-py37;' export 'PYTHON_HOME;' 'TCL_LIBRARY=/apps/miniconda3/4.10.3-py37/lib/tcl8.6;' export 'TCL_LIBRARY;' 'TK_LIBRARY=/apps/miniconda3/4.10.3-py37/lib/tk8.6;' export 'TK_LIBRARY;' '__LMOD_REF_COUNT__LMFILES_=/apps/lmodfiles/Core/xalt/latest.lua:1\;/apps/lmodfiles/Core/gcc-compatibility/8.4.0.lua:1\;/apps/lmodfiles/Core/intel/19.0.5.lua:1\;/apps/lmodfiles/Compiler/intel/19.0/mvapich2/2.3.3.lua:1\;/apps/lmodfiles/Core/modules/sp2020.lua:1\;/apps/lmodfiles/Core/miniconda3/4.10.3-py37.lua:1;' export '__LMOD_REF_COUNT__LMFILES_;' '_LMFILES_=/apps/lmodfiles/Core/xalt/latest.lua:/apps/lmodfiles/Core/gcc-compatibility/8.4.0.lua:/apps/lmodfiles/Core/intel/19.0.5.lua:/apps/lmodfiles/Compiler/intel/19.0/mvapich2/2.3.3.lua:/apps/lmodfiles/Core/modules/sp2020.lua:/apps/lmodfiles/Core/miniconda3/4.10.3-py37.lua;' export '_LMFILES_;' '_ModuleTable001_=X01vZHVsZVRhYmxlXz17WyJNVHZlcnNpb24iXT0zLFsiY19yZWJ1aWxkVGltZSJdPTg2NDAwLFsiY19zaG9ydFRpbWUiXT1mYWxzZSxkZXB0aFQ9e30sZmFtaWx5PXtbImNvbXBhdGliaWxpdHkiXT0iZ2NjLWNvbXBhdGliaWxpdHkiLFsiY29tcGlsZXIiXT0iaW50ZWwiLFsibXBpIl09Im12YXBpY2gyIixbInB5dGhvbiJdPSJtaW5pY29uZGEzIix9LG1UPXtbImdjYy1jb21wYXRpYmlsaXR5Il09e1siZm4iXT0iL2FwcHMvbG1vZGZpbGVzL0NvcmUvZ2NjLWNvbXBhdGliaWxpdHkvOC40LjAubHVhIixbImZ1bGxOYW1lIl09ImdjYy1jb21wYXRpYmlsaXR5LzguNC4wIixbImxvYWRPcmRlciJdPTIscHJvcFQ9e30sWyJzdGFja0RlcHRoIl09MixbInN0YXR1cyJdPSJhY3RpdmUi;' export '_ModuleTable001_;' '_ModuleTable002_=LFsidXNlck5hbWUiXT0iZ2NjLWNvbXBhdGliaWxpdHkvOC40LjAiLH0saW50ZWw9e1siZm4iXT0iL2FwcHMvbG1vZGZpbGVzL0NvcmUvaW50ZWwvMTkuMC41Lmx1YSIsWyJmdWxsTmFtZSJdPSJpbnRlbC8xOS4wLjUiLFsibG9hZE9yZGVyIl09Myxwcm9wVD17fSxbInN0YWNrRGVwdGgiXT0xLFsic3RhdHVzIl09ImFjdGl2ZSIsWyJ1c2VyTmFtZSJdPSJpbnRlbCIsfSxtaW5pY29uZGEzPXtbImZuIl09Ii9hcHBzL2xtb2RmaWxlcy9Db3JlL21pbmljb25kYTMvNC4xMC4zLXB5MzcubHVhIixbImZ1bGxOYW1lIl09Im1pbmljb25kYTMvNC4xMC4zLXB5MzciLFsibG9hZE9yZGVyIl09Nixwcm9wVD17fSxbInN0YWNrRGVwdGgiXT0wLFsic3RhdHVzIl09ImFjdGl2ZSIsWyJ1c2Vy;' export '_ModuleTable002_;' '_ModuleTable003_=TmFtZSJdPSJtaW5pY29uZGEzIix9LG1vZHVsZXM9e1siZm4iXT0iL2FwcHMvbG1vZGZpbGVzL0NvcmUvbW9kdWxlcy9zcDIwMjAubHVhIixbImZ1bGxOYW1lIl09Im1vZHVsZXMvc3AyMDIwIixbImxvYWRPcmRlciJdPTUscHJvcFQ9e30sWyJzdGFja0RlcHRoIl09MCxbInN0YXR1cyJdPSJhY3RpdmUiLFsidXNlck5hbWUiXT0ibW9kdWxlcyIsfSxtdmFwaWNoMj17WyJmbiJdPSIvYXBwcy9sbW9kZmlsZXMvQ29tcGlsZXIvaW50ZWwvMTkuMC9tdmFwaWNoMi8yLjMuMy5sdWEiLFsiZnVsbE5hbWUiXT0ibXZhcGljaDIvMi4zLjMiLFsibG9hZE9yZGVyIl09NCxwcm9wVD17fSxbInN0YWNrRGVwdGgiXT0xLFsic3RhdHVzIl09ImFjdGl2ZSIsWyJ1c2VyTmFtZSJdPSJtdmFwaWNo;' export '_ModuleTable003_;' '_ModuleTable004_=MiIsfSx4YWx0PXtbImZuIl09Ii9hcHBzL2xtb2RmaWxlcy9Db3JlL3hhbHQvbGF0ZXN0Lmx1YSIsWyJmdWxsTmFtZSJdPSJ4YWx0L2xhdGVzdCIsWyJsb2FkT3JkZXIiXT0xLHByb3BUPXt9LFsic3RhY2tEZXB0aCJdPTEsWyJzdGF0dXMiXT0iYWN0aXZlIixbInVzZXJOYW1lIl09InhhbHQiLH0sfSxtcGF0aEE9eyIvYXBwcy9sbW9kZmlsZXMvTVBJL2ludGVsLzE5LjAvbXZhcGljaDIvMi4zIiwiL2FwcHMvbG1vZGZpbGVzL0NvbXBpbGVyL2ludGVsLzE5LjAiLCIvYXBwcy9sbW9kZmlsZXMvTGludXgiLCIvYXBwcy9sbW9kZmlsZXMvQ29yZSIsIi9hcHBzL2xtb2QvbG1vZC9tb2R1bGVmaWxlcy9Db3JlIix9LFsic3lzdGVtQmFzZU1QQVRIIl09Ii9hcHBzL2xtb2RmaWxlcy9M;' export '_ModuleTable004_;' '_ModuleTable005_=aW51eDovYXBwcy9sbW9kZmlsZXMvQ29yZTovYXBwcy9sbW9kL2xtb2QvbW9kdWxlZmlsZXMvQ29yZSIsfQ==;' export '_ModuleTable005_;' '_ModuleTable_Sz_=5;' export '_ModuleTable_Sz_;'
++ __LMOD_REF_COUNT_LD_LIBRARY_PATH='/apps/miniconda3/4.10.3-py37/lib:1;/opt/mvapich2/intel/19.0/2.3.3/lib:1;/apps/gnu/8.4.0/lib64:1;/apps/gnu/8.4.0/lib:1;/opt/intel/19.0.5/debugger_2019/libipt/intel64/lib:1;/opt/intel/19.0.5/compilers_and_libraries_2019/linux/lib/intel64_lin:1;/opt/intel/19.0.5/compilers_and_libraries_2019/linux/daal/lib/intel64_lin:1;/opt/intel/19.0.5/compilers_and_libraries_2019/linux/ipp/lib/intel64_lin:1;/opt/intel/19.0.5/compilers_and_libraries_2019/linux/mkl/lib/intel64_lin:1;/opt/intel/19.0.5/compilers_and_libraries_2019/linux/tbb/lib/intel64_lin/gcc4.4:1;/opt/ddn/cci/lib:1;/opt/ddn/ime/lib:1;/opt/ddn/isa-l/lib:1'
++ export __LMOD_REF_COUNT_LD_LIBRARY_PATH
++ LD_LIBRARY_PATH=/apps/miniconda3/4.10.3-py37/lib:/opt/mvapich2/intel/19.0/2.3.3/lib:/apps/gnu/8.4.0/lib64:/apps/gnu/8.4.0/lib:/opt/intel/19.0.5/debugger_2019/libipt/intel64/lib:/opt/intel/19.0.5/compilers_and_libraries_2019/linux/lib/intel64_lin:/opt/intel/19.0.5/compilers_and_libraries_2019/linux/daal/lib/intel64_lin:/opt/intel/19.0.5/compilers_and_libraries_2019/linux/ipp/lib/intel64_lin:/opt/intel/19.0.5/compilers_and_libraries_2019/linux/mkl/lib/intel64_lin:/opt/intel/19.0.5/compilers_and_libraries_2019/linux/tbb/lib/intel64_lin/gcc4.4:/opt/ddn/cci/lib:/opt/ddn/ime/lib:/opt/ddn/isa-l/lib
++ export LD_LIBRARY_PATH
++ LMOD_FAMILY_PYTHON=miniconda3
++ export LMOD_FAMILY_PYTHON
++ LMOD_FAMILY_PYTHON_VERSION=4.10.3-py37
++ export LMOD_FAMILY_PYTHON_VERSION
++ __LMOD_REF_COUNT_LOADEDMODULES='xalt/latest:1;gcc-compatibility/8.4.0:1;intel/19.0.5:1;mvapich2/2.3.3:1;modules/sp2020:1;miniconda3/4.10.3-py37:1'
++ export __LMOD_REF_COUNT_LOADEDMODULES
++ LOADEDMODULES=xalt/latest:gcc-compatibility/8.4.0:intel/19.0.5:mvapich2/2.3.3:modules/sp2020:miniconda3/4.10.3-py37
++ export LOADEDMODULES
++ __LMOD_REF_COUNT_MANPATH='/apps/miniconda3/4.10.3-py37/share/man:1;/opt/mvapich2/intel/19.0/2.3.3/share/man:1;/opt/intel/19.0.5/itac_latest/man:1;/opt/intel/19.0.5/documentation_2019/en/debugger/gdb-igfx/man:1;/opt/intel/19.0.5/inspector_2019/man:1;/opt/intel/19.0.5/compilers_and_libraries_2019/linux/man/common:1;/apps/lmod/lmod/share/man:1;/opt/puppetlabs/puppet/share/man:1;/opt/intel/19.0.5/vtune_amplifier/man:1;/opt/intel/19.0.5/advisor/man:1'
++ export __LMOD_REF_COUNT_MANPATH
++ MANPATH=/apps/miniconda3/4.10.3-py37/share/man:/opt/mvapich2/intel/19.0/2.3.3/share/man:/opt/intel/19.0.5/itac_latest/man:/opt/intel/19.0.5/documentation_2019/en/debugger/gdb-igfx/man:/opt/intel/19.0.5/inspector_2019/man:/opt/intel/19.0.5/compilers_and_libraries_2019/linux/man/common:/apps/lmod/lmod/share/man::/opt/puppetlabs/puppet/share/man:/opt/intel/19.0.5/vtune_amplifier/man:/opt/intel/19.0.5/advisor/man
++ export MANPATH
++ MODULEPATH=/apps/lmodfiles/MPI/intel/19.0/mvapich2/2.3:/apps/lmodfiles/Compiler/intel/19.0:/apps/lmodfiles/Linux:/apps/lmodfiles/Core:/apps/lmod/lmod/modulefiles/Core
++ export MODULEPATH
++ OSC_FAMILY_PYTHON=miniconda3
++ export OSC_FAMILY_PYTHON
++ OSC_FAMILY_PYTHON_VERSION=4.10.3-py37
++ export OSC_FAMILY_PYTHON_VERSION
++ OSC_MINICONDA3_DIR=/apps/miniconda3/4.10.3-py37
++ export OSC_MINICONDA3_DIR
++ __LMOD_REF_COUNT_PATH='/apps/xalt/xalt/bin:1;/apps/miniconda3/4.10.3-py37/bin:1;/usr/local/miniconda3/4.10.3-py37/bin:3;/opt/osc/bin:3;/users/PDS0325/sachitk26/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/bin/remote-cli:1;/opt/mvapich2/intel/19.0/2.3.3/bin:1;/apps/gnu/8.4.0/bin:1;/opt/intel/19.0.5/itac_latest/bin:1;/opt/intel/19.0.5/advisor/bin64:1;/opt/intel/19.0.5/vtune_amplifier/bin64:1;/opt/intel/19.0.5/inspector_2019/bin64:1;/opt/intel/19.0.5/compilers_and_libraries_2019/linux/bin/intel64:1;/usr/lib64/qt-3.3/bin:1;/usr/local/bin:1;/usr/bin:1;/opt/puppetlabs/bin:1;/users/PDS0325/sachitk26/local/ont-guppy/bin:3;/usr/local/sbin:1;/usr/sbin:1'
++ export __LMOD_REF_COUNT_PATH
++ PATH=/apps/xalt/xalt/bin:/apps/miniconda3/4.10.3-py37/bin:/usr/local/miniconda3/4.10.3-py37/bin:/opt/osc/bin:/users/PDS0325/sachitk26/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/bin/remote-cli:/opt/mvapich2/intel/19.0/2.3.3/bin:/apps/gnu/8.4.0/bin:/opt/intel/19.0.5/itac_latest/bin:/opt/intel/19.0.5/advisor/bin64:/opt/intel/19.0.5/vtune_amplifier/bin64:/opt/intel/19.0.5/inspector_2019/bin64:/opt/intel/19.0.5/compilers_and_libraries_2019/linux/bin/intel64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/opt/puppetlabs/bin:/users/PDS0325/sachitk26/local/ont-guppy/bin:/usr/local/sbin:/usr/sbin
++ export PATH
++ PYTHON_HOME=/apps/miniconda3/4.10.3-py37
++ export PYTHON_HOME
++ TCL_LIBRARY=/apps/miniconda3/4.10.3-py37/lib/tcl8.6
++ export TCL_LIBRARY
++ TK_LIBRARY=/apps/miniconda3/4.10.3-py37/lib/tk8.6
++ export TK_LIBRARY
++ __LMOD_REF_COUNT__LMFILES_='/apps/lmodfiles/Core/xalt/latest.lua:1;/apps/lmodfiles/Core/gcc-compatibility/8.4.0.lua:1;/apps/lmodfiles/Core/intel/19.0.5.lua:1;/apps/lmodfiles/Compiler/intel/19.0/mvapich2/2.3.3.lua:1;/apps/lmodfiles/Core/modules/sp2020.lua:1;/apps/lmodfiles/Core/miniconda3/4.10.3-py37.lua:1'
++ export __LMOD_REF_COUNT__LMFILES_
++ _LMFILES_=/apps/lmodfiles/Core/xalt/latest.lua:/apps/lmodfiles/Core/gcc-compatibility/8.4.0.lua:/apps/lmodfiles/Core/intel/19.0.5.lua:/apps/lmodfiles/Compiler/intel/19.0/mvapich2/2.3.3.lua:/apps/lmodfiles/Core/modules/sp2020.lua:/apps/lmodfiles/Core/miniconda3/4.10.3-py37.lua
++ export _LMFILES_
++ _ModuleTable001_=X01vZHVsZVRhYmxlXz17WyJNVHZlcnNpb24iXT0zLFsiY19yZWJ1aWxkVGltZSJdPTg2NDAwLFsiY19zaG9ydFRpbWUiXT1mYWxzZSxkZXB0aFQ9e30sZmFtaWx5PXtbImNvbXBhdGliaWxpdHkiXT0iZ2NjLWNvbXBhdGliaWxpdHkiLFsiY29tcGlsZXIiXT0iaW50ZWwiLFsibXBpIl09Im12YXBpY2gyIixbInB5dGhvbiJdPSJtaW5pY29uZGEzIix9LG1UPXtbImdjYy1jb21wYXRpYmlsaXR5Il09e1siZm4iXT0iL2FwcHMvbG1vZGZpbGVzL0NvcmUvZ2NjLWNvbXBhdGliaWxpdHkvOC40LjAubHVhIixbImZ1bGxOYW1lIl09ImdjYy1jb21wYXRpYmlsaXR5LzguNC4wIixbImxvYWRPcmRlciJdPTIscHJvcFQ9e30sWyJzdGFja0RlcHRoIl09MixbInN0YXR1cyJdPSJhY3RpdmUi
++ export _ModuleTable001_
++ _ModuleTable002_=LFsidXNlck5hbWUiXT0iZ2NjLWNvbXBhdGliaWxpdHkvOC40LjAiLH0saW50ZWw9e1siZm4iXT0iL2FwcHMvbG1vZGZpbGVzL0NvcmUvaW50ZWwvMTkuMC41Lmx1YSIsWyJmdWxsTmFtZSJdPSJpbnRlbC8xOS4wLjUiLFsibG9hZE9yZGVyIl09Myxwcm9wVD17fSxbInN0YWNrRGVwdGgiXT0xLFsic3RhdHVzIl09ImFjdGl2ZSIsWyJ1c2VyTmFtZSJdPSJpbnRlbCIsfSxtaW5pY29uZGEzPXtbImZuIl09Ii9hcHBzL2xtb2RmaWxlcy9Db3JlL21pbmljb25kYTMvNC4xMC4zLXB5MzcubHVhIixbImZ1bGxOYW1lIl09Im1pbmljb25kYTMvNC4xMC4zLXB5MzciLFsibG9hZE9yZGVyIl09Nixwcm9wVD17fSxbInN0YWNrRGVwdGgiXT0wLFsic3RhdHVzIl09ImFjdGl2ZSIsWyJ1c2Vy
++ export _ModuleTable002_
++ _ModuleTable003_=TmFtZSJdPSJtaW5pY29uZGEzIix9LG1vZHVsZXM9e1siZm4iXT0iL2FwcHMvbG1vZGZpbGVzL0NvcmUvbW9kdWxlcy9zcDIwMjAubHVhIixbImZ1bGxOYW1lIl09Im1vZHVsZXMvc3AyMDIwIixbImxvYWRPcmRlciJdPTUscHJvcFQ9e30sWyJzdGFja0RlcHRoIl09MCxbInN0YXR1cyJdPSJhY3RpdmUiLFsidXNlck5hbWUiXT0ibW9kdWxlcyIsfSxtdmFwaWNoMj17WyJmbiJdPSIvYXBwcy9sbW9kZmlsZXMvQ29tcGlsZXIvaW50ZWwvMTkuMC9tdmFwaWNoMi8yLjMuMy5sdWEiLFsiZnVsbE5hbWUiXT0ibXZhcGljaDIvMi4zLjMiLFsibG9hZE9yZGVyIl09NCxwcm9wVD17fSxbInN0YWNrRGVwdGgiXT0xLFsic3RhdHVzIl09ImFjdGl2ZSIsWyJ1c2VyTmFtZSJdPSJtdmFwaWNo
++ export _ModuleTable003_
++ _ModuleTable004_=MiIsfSx4YWx0PXtbImZuIl09Ii9hcHBzL2xtb2RmaWxlcy9Db3JlL3hhbHQvbGF0ZXN0Lmx1YSIsWyJmdWxsTmFtZSJdPSJ4YWx0L2xhdGVzdCIsWyJsb2FkT3JkZXIiXT0xLHByb3BUPXt9LFsic3RhY2tEZXB0aCJdPTEsWyJzdGF0dXMiXT0iYWN0aXZlIixbInVzZXJOYW1lIl09InhhbHQiLH0sfSxtcGF0aEE9eyIvYXBwcy9sbW9kZmlsZXMvTVBJL2ludGVsLzE5LjAvbXZhcGljaDIvMi4zIiwiL2FwcHMvbG1vZGZpbGVzL0NvbXBpbGVyL2ludGVsLzE5LjAiLCIvYXBwcy9sbW9kZmlsZXMvTGludXgiLCIvYXBwcy9sbW9kZmlsZXMvQ29yZSIsIi9hcHBzL2xtb2QvbG1vZC9tb2R1bGVmaWxlcy9Db3JlIix9LFsic3lzdGVtQmFzZU1QQVRIIl09Ii9hcHBzL2xtb2RmaWxlcy9M
++ export _ModuleTable004_
++ _ModuleTable005_=aW51eDovYXBwcy9sbW9kZmlsZXMvQ29yZTovYXBwcy9sbW9kL2xtb2QvbW9kdWxlZmlsZXMvQ29yZSIsfQ==
++ export _ModuleTable005_
++ _ModuleTable_Sz_=5
++ export _ModuleTable_Sz_
++ : -s sh
+ eval
+ source activate local
++ _CONDA_ROOT=/apps/miniconda3/4.10.3-py37
++ . /apps/miniconda3/4.10.3-py37/etc/profile.d/conda.sh
+++ export CONDA_EXE=/apps/miniconda3/4.10.3-py37/bin/conda
+++ CONDA_EXE=/apps/miniconda3/4.10.3-py37/bin/conda
+++ export _CE_M=
+++ _CE_M=
+++ export _CE_CONDA=
+++ _CE_CONDA=
+++ export CONDA_PYTHON_EXE=/apps/miniconda3/4.10.3-py37/bin/python
+++ CONDA_PYTHON_EXE=/apps/miniconda3/4.10.3-py37/bin/python
+++ '[' -z '' ']'
+++ export CONDA_SHLVL=0
+++ CONDA_SHLVL=0
+++ '[' -n '' ']'
+++++ dirname /apps/miniconda3/4.10.3-py37/bin/conda
++++ dirname /apps/miniconda3/4.10.3-py37/bin
+++ PATH=/apps/miniconda3/4.10.3-py37/condabin:/apps/xalt/xalt/bin:/apps/miniconda3/4.10.3-py37/bin:/usr/local/miniconda3/4.10.3-py37/bin:/opt/osc/bin:/users/PDS0325/sachitk26/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/bin/remote-cli:/opt/mvapich2/intel/19.0/2.3.3/bin:/apps/gnu/8.4.0/bin:/opt/intel/19.0.5/itac_latest/bin:/opt/intel/19.0.5/advisor/bin64:/opt/intel/19.0.5/vtune_amplifier/bin64:/opt/intel/19.0.5/inspector_2019/bin64:/opt/intel/19.0.5/compilers_and_libraries_2019/linux/bin/intel64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/opt/puppetlabs/bin:/users/PDS0325/sachitk26/local/ont-guppy/bin:/usr/local/sbin:/usr/sbin
+++ export PATH
+++ '[' -z '' ']'
+++ PS1=
++ conda activate local
++ local cmd=activate
++ case "$cmd" in
++ __conda_activate activate local
++ '[' -n '' ']'
++ local ask_conda
+++ PS1=
+++ __conda_exe shell.posix activate local
+++ __add_sys_prefix_to_path
+++ '[' -n '' ']'
++++ dirname /apps/miniconda3/4.10.3-py37/bin/conda
+++ SYSP=/apps/miniconda3/4.10.3-py37/bin
++++ dirname /apps/miniconda3/4.10.3-py37/bin
+++ SYSP=/apps/miniconda3/4.10.3-py37
+++ '[' -n '' ']'
+++ PATH=/apps/miniconda3/4.10.3-py37/bin:/apps/miniconda3/4.10.3-py37/condabin:/apps/xalt/xalt/bin:/apps/miniconda3/4.10.3-py37/bin:/usr/local/miniconda3/4.10.3-py37/bin:/opt/osc/bin:/users/PDS0325/sachitk26/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/bin/remote-cli:/opt/mvapich2/intel/19.0/2.3.3/bin:/apps/gnu/8.4.0/bin:/opt/intel/19.0.5/itac_latest/bin:/opt/intel/19.0.5/advisor/bin64:/opt/intel/19.0.5/vtune_amplifier/bin64:/opt/intel/19.0.5/inspector_2019/bin64:/opt/intel/19.0.5/compilers_and_libraries_2019/linux/bin/intel64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/opt/puppetlabs/bin:/users/PDS0325/sachitk26/local/ont-guppy/bin:/usr/local/sbin:/usr/sbin
+++ export PATH
+++ /apps/miniconda3/4.10.3-py37/bin/conda shell.posix activate local
++ ask_conda='PS1='\''(local) '\''
export PATH='\''/users/PDS0325/sachitk26/.conda/envs/local/bin:/apps/miniconda3/4.10.3-py37/condabin:/apps/xalt/xalt/bin:/apps/miniconda3/4.10.3-py37/bin:/usr/local/miniconda3/4.10.3-py37/bin:/opt/osc/bin:/users/PDS0325/sachitk26/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/bin/remote-cli:/opt/mvapich2/intel/19.0/2.3.3/bin:/apps/gnu/8.4.0/bin:/opt/intel/19.0.5/itac_latest/bin:/opt/intel/19.0.5/advisor/bin64:/opt/intel/19.0.5/vtune_amplifier/bin64:/opt/intel/19.0.5/inspector_2019/bin64:/opt/intel/19.0.5/compilers_and_libraries_2019/linux/bin/intel64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/opt/puppetlabs/bin:/users/PDS0325/sachitk26/local/ont-guppy/bin:/usr/local/sbin:/usr/sbin'\''
export CONDA_PREFIX='\''/users/PDS0325/sachitk26/.conda/envs/local'\''
export CONDA_SHLVL='\''1'\''
export CONDA_DEFAULT_ENV='\''local'\''
export CONDA_PROMPT_MODIFIER='\''(local) '\''
export CONDA_EXE='\''/apps/miniconda3/4.10.3-py37/bin/conda'\''
export _CE_M='\'''\''
export _CE_CONDA='\'''\''
export CONDA_PYTHON_EXE='\''/apps/miniconda3/4.10.3-py37/bin/python'\'''
++ eval 'PS1='\''(local) '\''
export PATH='\''/users/PDS0325/sachitk26/.conda/envs/local/bin:/apps/miniconda3/4.10.3-py37/condabin:/apps/xalt/xalt/bin:/apps/miniconda3/4.10.3-py37/bin:/usr/local/miniconda3/4.10.3-py37/bin:/opt/osc/bin:/users/PDS0325/sachitk26/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/bin/remote-cli:/opt/mvapich2/intel/19.0/2.3.3/bin:/apps/gnu/8.4.0/bin:/opt/intel/19.0.5/itac_latest/bin:/opt/intel/19.0.5/advisor/bin64:/opt/intel/19.0.5/vtune_amplifier/bin64:/opt/intel/19.0.5/inspector_2019/bin64:/opt/intel/19.0.5/compilers_and_libraries_2019/linux/bin/intel64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/opt/puppetlabs/bin:/users/PDS0325/sachitk26/local/ont-guppy/bin:/usr/local/sbin:/usr/sbin'\''
export CONDA_PREFIX='\''/users/PDS0325/sachitk26/.conda/envs/local'\''
export CONDA_SHLVL='\''1'\''
export CONDA_DEFAULT_ENV='\''local'\''
export CONDA_PROMPT_MODIFIER='\''(local) '\''
export CONDA_EXE='\''/apps/miniconda3/4.10.3-py37/bin/conda'\''
export _CE_M='\'''\''
export _CE_CONDA='\'''\''
export CONDA_PYTHON_EXE='\''/apps/miniconda3/4.10.3-py37/bin/python'\'''
+++ PS1='(local) '
+++ export PATH=/users/PDS0325/sachitk26/.conda/envs/local/bin:/apps/miniconda3/4.10.3-py37/condabin:/apps/xalt/xalt/bin:/apps/miniconda3/4.10.3-py37/bin:/usr/local/miniconda3/4.10.3-py37/bin:/opt/osc/bin:/users/PDS0325/sachitk26/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/bin/remote-cli:/opt/mvapich2/intel/19.0/2.3.3/bin:/apps/gnu/8.4.0/bin:/opt/intel/19.0.5/itac_latest/bin:/opt/intel/19.0.5/advisor/bin64:/opt/intel/19.0.5/vtune_amplifier/bin64:/opt/intel/19.0.5/inspector_2019/bin64:/opt/intel/19.0.5/compilers_and_libraries_2019/linux/bin/intel64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/opt/puppetlabs/bin:/users/PDS0325/sachitk26/local/ont-guppy/bin:/usr/local/sbin:/usr/sbin
+++ PATH=/users/PDS0325/sachitk26/.conda/envs/local/bin:/apps/miniconda3/4.10.3-py37/condabin:/apps/xalt/xalt/bin:/apps/miniconda3/4.10.3-py37/bin:/usr/local/miniconda3/4.10.3-py37/bin:/opt/osc/bin:/users/PDS0325/sachitk26/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/bin/remote-cli:/opt/mvapich2/intel/19.0/2.3.3/bin:/apps/gnu/8.4.0/bin:/opt/intel/19.0.5/itac_latest/bin:/opt/intel/19.0.5/advisor/bin64:/opt/intel/19.0.5/vtune_amplifier/bin64:/opt/intel/19.0.5/inspector_2019/bin64:/opt/intel/19.0.5/compilers_and_libraries_2019/linux/bin/intel64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/opt/puppetlabs/bin:/users/PDS0325/sachitk26/local/ont-guppy/bin:/usr/local/sbin:/usr/sbin
+++ export CONDA_PREFIX=/users/PDS0325/sachitk26/.conda/envs/local
+++ CONDA_PREFIX=/users/PDS0325/sachitk26/.conda/envs/local
+++ export CONDA_SHLVL=1
+++ CONDA_SHLVL=1
+++ export CONDA_DEFAULT_ENV=local
+++ CONDA_DEFAULT_ENV=local
+++ export 'CONDA_PROMPT_MODIFIER=(local) '
+++ CONDA_PROMPT_MODIFIER='(local) '
+++ export CONDA_EXE=/apps/miniconda3/4.10.3-py37/bin/conda
+++ CONDA_EXE=/apps/miniconda3/4.10.3-py37/bin/conda
+++ export _CE_M=
+++ _CE_M=
+++ export _CE_CONDA=
+++ _CE_CONDA=
+++ export CONDA_PYTHON_EXE=/apps/miniconda3/4.10.3-py37/bin/python
+++ CONDA_PYTHON_EXE=/apps/miniconda3/4.10.3-py37/bin/python
++ __conda_hashr
++ '[' -n '' ']'
++ '[' -n '' ']'
++ hash -r
+ mpiexec python filter_BAM_plots.py /users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/picks /users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    self.canvas.print_figure(fname, **kwargs)
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR8173239#TPP#NC_000913.3#4196280#4196180#-.png'
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR7154634#TPP#NC_000913.3#4196280#4196180#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR7154624#TPP#NC_000913.3#4196280#4196180#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/Cobalamin.SRR8218076#Cobalamin#NC_000913.3#4163384#4163573#+.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/pass/Cobalamin.SRR8164487#Cobalamin#NC_000913.3#4163384#4163573#+.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/Cobalamin.SRR8173217#Cobalamin#NC_000913.3#4163384#4163573#+.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/pass/Cobalamin.SRR7154637#Cobalamin#NC_000913.3#4163384#4163573#+.png'
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/Cobalamin.SRR9204648#Cobalamin#NC_000913.3#4163384#4163573#+.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR7154627#TPP#NC_000913.3#75610#75511#-.png'
    fp = builtins.open(filename, "w+b")
    fp = builtins.open(filename, "w+b")
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/Cobalamin.SRR8173249#Cobalamin#NC_000913.3#4163384#4163573#+.png'
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/Cobalamin.SRR8164484#Cobalamin#NC_000913.3#4163384#4163573#+.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/Cobalamin.SRR8173241#Cobalamin#NC_000913.3#4163384#4163573#+.png'
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/Cobalamin.SRR9204650#Cobalamin#NC_000913.3#4163384#4163573#+.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR8164486#TPP#NC_000913.3#75610#75511#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR7154638#TPP#NC_000913.3#2185432#2185336#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/MOCO_RNA_motif.SRR8218076#MOCO_RNA_motif#NC_000913.3#816912#817056#+.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR7154645#TPP#NC_000913.3#4196280#4196180#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR8164485#TPP#NC_000913.3#4196280#4196180#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/pass/Mg_sensor.SRR8218078#Mg_sensor#NC_000913.3#4467416#4467531#+.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR7154628#TPP#NC_000913.3#4196280#4196180#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR8173249#TPP#NC_000913.3#4196280#4196180#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR8173244#TPP#NC_000913.3#4196280#4196180#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR8173211#TPP#NC_000913.3#4196280#4196180#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR8173210#TPP#NC_000913.3#4196280#4196180#-.png'
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR7154625#TPP#NC_000913.3#4196280#4196180#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR8173229#TPP#NC_000913.3#4196280#4196180#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR9204651#TPP#NC_000913.3#4196280#4196180#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR8173243#TPP#NC_000913.3#4196280#4196180#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR8218077#TPP#NC_000913.3#4196280#4196180#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR8218065#TPP#NC_000913.3#4196280#4196180#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR8218074#TPP#NC_000913.3#4196280#4196180#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR8173212#TPP#NC_000913.3#4196280#4196180#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR8164477#TPP#NC_000913.3#4196280#4196180#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR8173232#TPP#NC_000913.3#4196280#4196180#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR8173237#TPP#NC_000913.3#4196280#4196180#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR8173247#TPP#NC_000913.3#4196280#4196180#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR8164483#TPP#NC_000913.3#4196280#4196180#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR8173217#TPP#NC_000913.3#4196280#4196180#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR8173242#TPP#NC_000913.3#4196280#4196180#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR7154635#TPP#NC_000913.3#2185432#2185336#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/TPP.SRR8164482#TPP#NC_000913.3#4196280#4196180#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/MOCO_RNA_motif.SRR7154644#MOCO_RNA_motif#NC_000913.3#816912#817056#+.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/pass/Mg_sensor.SRR8173227#Mg_sensor#NC_000913.3#4467416#4467531#+.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/MOCO_RNA_motif.SRR8173210#MOCO_RNA_motif#NC_000913.3#816912#817056#+.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/MOCO_RNA_motif.SRR8218075#MOCO_RNA_motif#NC_000913.3#816912#817056#+.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/MOCO_RNA_motif.SRR8173212#MOCO_RNA_motif#NC_000913.3#816912#817056#+.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/FMN.SRR8173212#FMN#NC_000913.3#3184718#3184570#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/MOCO_RNA_motif.SRR8218077#MOCO_RNA_motif#NC_000913.3#816912#817056#+.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/FMN.SRR7154637#FMN#NC_000913.3#3184718#3184570#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/MOCO_RNA_motif.SRR8164480#MOCO_RNA_motif#NC_000913.3#816912#817056#+.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/FMN.SRR8173221#FMN#NC_000913.3#3184718#3184570#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/pass/Mg_sensor.SRR9204649#Mg_sensor#NC_000913.3#4467416#4467531#+.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/FMN.SRR8218068#FMN#NC_000913.3#3184718#3184570#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/MOCO_RNA_motif.SRR8173233#MOCO_RNA_motif#NC_000913.3#816912#817056#+.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/FMN.SRR8173228#FMN#NC_000913.3#3184718#3184570#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/pass/Mg_sensor.SRR8173230#Mg_sensor#NC_000913.3#4467416#4467531#+.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/MOCO_RNA_motif.SRR7154641#MOCO_RNA_motif#NC_000913.3#816912#817056#+.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/Lysine.SRR8164481#Lysine#NC_000913.3#4233521#4233325#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/Mg_sensor.SRR8173222#Mg_sensor#NC_000913.3#4467416#4467531#+.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/FMN.SRR8173244#FMN#NC_000913.3#3184718#3184570#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/FMN.SRR8173231#FMN#NC_000913.3#3184718#3184570#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/MOCO_RNA_motif.SRR7154631#MOCO_RNA_motif#NC_000913.3#816912#817056#+.png'
    fp = builtins.open(filename, "w+b")
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/Lysine.SRR8173231#Lysine#NC_000913.3#4233521#4233325#-.png'
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/FMN.SRR7154639#FMN#NC_000913.3#3184718#3184570#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/Mg_sensor.SRR8173217#Mg_sensor#NC_000913.3#4467416#4467531#+.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/FMN.SRR7154628#FMN#NC_000913.3#3184718#3184570#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/FMN.SRR8173234#FMN#NC_000913.3#3184718#3184570#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/Mg_sensor.SRR9204648#Mg_sensor#NC_000913.3#4467416#4467531#+.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/pass/Mg_sensor.SRR7154626#Mg_sensor#NC_000913.3#4467416#4467531#+.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/pass/Mg_sensor.SRR8173233#Mg_sensor#NC_000913.3#4467416#4467531#+.png'
    fp = builtins.open(filename, "w+b")
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/Mg_sensor.SRR8164485#Mg_sensor#NC_000913.3#4467416#4467531#+.png'
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/Cobalamin.SRR8218067#Cobalamin#NC_000913.3#4163384#4163573#+.png'
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/Lysine.SRR8173221#Lysine#NC_000913.3#4233521#4233325#-.png'
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/Lysine.SRR8218066#Lysine#NC_000913.3#4233521#4233325#-.png'
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/Lysine.SRR8173219#Lysine#NC_000913.3#4233521#4233325#-.png'
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/Lysine.SRR8218077#Lysine#NC_000913.3#4233521#4233325#-.png'
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/Lysine.SRR8173238#Lysine#NC_000913.3#4233521#4233325#-.png'
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/Lysine.SRR8173217#Lysine#NC_000913.3#4233521#4233325#-.png'
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/Lysine.SRR7154625#Lysine#NC_000913.3#4233521#4233325#-.png'
Traceback (most recent call last):
  File "/users/PDS0325/sachitk26/packages/tart/validation/alignment/filter_BAM_plots.py", line 83, in <module>
    plot_gen(
  File "/users/PDS0325/sachitk26/packages/tart/parsefuncs.py", line 710, in plot_gen
    fig.savefig(f"{save_path}")
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/figure.py", line 3378, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    result = print_method(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    mpl.image.imsave(
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/matplotlib/image.py", line 1689, in imsave
    image.save(fname, **pil_kwargs)
  File "/users/PDS0325/sachitk26/.conda/envs/local/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/filtered/fail/Lysine.SRR9204652#Lysine#NC_000913.3#4233521#4233325#-.png'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[54202,1],69]
  Exit code:    1
--------------------------------------------------------------------------
